--textures
resource.AddSingleFile("materials/flexbox/barry_red.png")
resource.AddSingleFile("materials/flexbox/barry_blue.png")
resource.AddSingleFile("materials/flexbox/barry_lemon.png")
resource.AddSingleFile("materials/flexbox/barry_orange.png")
resource.AddSingleFile("materials/flexbox/barry_tea.png")
--icons
resource.AddSingleFile("materials/flexbox/logo_b1.png")
resource.AddSingleFile("materials/flexbox/logo_b1is.png")
resource.AddSingleFile("materials/flexbox/logo_lua.png")